AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates resources that will used in the blog Simplifying Patient Care with a Custom Voice Assistant. **WARNING** This template creates a Lambda Function, DynamoDB table and related resources. You will be billed for the AWS resources used if you create a stack from this template.
Resources:
  GetPatientDataLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_patient_data.lambda_handler
      Runtime: python3.8
      CodeUri: 's3://davidqiutest/get_patient_data.py.zip'
      Role: !GetAtt GetPatientDataRole.Arn
      Timeout: 30
      Environment:
        Variables:
          PATIENT_TABLE: PatientSensorInformation

  GetPatientDataRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action: "sts:AssumeRole"
          Principal:
            Service:
            - "lambda.amazonaws.com"
      Path: "/"

  GetPatientDataRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GetPatientDataRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action: dynamodb:Query
          Resource: !GetAtt PatientSensorInformationTable.Arn
      Roles:
      - !Ref GetPatientDataRole


  PatientSensorInformationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: PATIENT_ID
        AttributeType: S
      - AttributeName: TIMESTAMP
        AttributeType: S
      KeySchema:
      - AttributeName: PATIENT_ID
        KeyType: HASH
      - AttributeName: TIMESTAMP
        KeyType: RANGE
      TableName: PatientSensorInformation
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
